version: "3.1"
services:
  client:
    image: duchungho/client-inf:latest
    restart: always
    networks:
      - bridge
    ports:
      - 3000:3000
    env_file:
      - .env

networks:
  bridge:
volumes:
  db_data:
