version: '3.1'
services:
  api:
    image: duchungho/inf-sprint:latest
    restart: always
    networks:
      - bridge
    ports:
      - 8081:8081

  client:
    image: duchungho/client-inf:latest
    restart: always
    networks:
      - bridge
    ports:
      - 3000:3000

networks:
  bridge:
volumes:
  mysql: