version: "3.1"
services:
  # api:
  #   image: duchungho/inf-sprint:latest
  #   restart: always
  #   networks:
  #     - bridge
  #   ports:
  #     - 8081:8081

  # client:
  #   image: duchungho/client-inf:latest
  #   restart: always
  #   networks:
  #     - bridge
  #   ports:
  #     - 3000:3000

  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: document-db
      MYSQL_PASSWORD: password
    networks:
      - bridge

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bridge

networks:
  bridge:
volumes:
  db_data:
