name: Deploy API & Client

on:
  push:
    branches:
      - test-cd

jobs:
  deploy-server:
    # needs: [build-api]
    name: Deploy Preview API
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: ENV file
        run: echo ${{ secrets.DOCKERHUB_USERNAME }} > application.properties

      - name: Login to Docker Hub
        run: docker compose down

      - name: Login to Docker Hub
        run: docker compose up -d
